spring:
  application:
    name: toto
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
  datasource:
    url: jdbc:mariadb://localhost:3306/muky_toto
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  liquibase:
    change-log: classpath:mariadb/db.changelog-master.xml
    enabled: true


app:
  league:
    israel:
      season_id: 27
      leagues:
        - type: NATIONAL_LEAGUE
          name: לאומית
          league_id: 45
          team:
            '1003': מכבי הרצליה
            '5775': מכבי יפו
            '2186': הפועל חדרה
            '2252': הפועל כפר שלם
        - type: WINNER
          name: winner
          league_id: 40
          team:
            '2171': הפועל באר שבע
            '1061': מכבי תל אביב
            '3595': ביתר ירושלים
            '1068': מכבי נתניה
            '2176': הפועל תל אביב
            '1198': מעודון ספורט אשדוד
            '4823': בני סכנין
            '1005': מכבי חיפה
            '2170': הפועל חיפה
            '2182': הפועל קרית שמונה
            '2173': הפועל פתח תקוה
            '5455': עירוני דורות טבריה
            '5981': הפועל ירושלים
            '5257': מכבי בני ריינה











