spring:
  application:
    name: toto
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o
  mail:
    host: smtp.gmail.com
    port: 587
    username: aifootballpredictor@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

redis:
  host: ${REDIS_HOST:redis-18068.c83.us-east-1-2.ec2.cloud.redislabs.com}
  port: ${REDIS_PORT:18068}
  password: ${REDIS_PASSWORD}
  expire-seconds: ${REDIS_EXPIRE_SECONDS:86400}

feedback:
  recipient:
    email: aifootballpredictor@gmail.com

# Custom properties for Perplexity
custom:
  ai:
    perplexity:
      api-key: ${PERPLEXITY_API_KEY}
      base-url: https://api.perplexity.ai

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

app:
  min-version: ${APP_MIN_VERSION:1.0.1+36}
  api-football:
    api-key: ${API_FOOTBALL_KEY}
  predefined-events:
    winner16: ${WINNER_16:1379143-1379142-1379148-1379141-1379140-1378033-1386832-1386834-1386830-1386831-1386836-1386828}
    winner16World: ${WINNER_16_WORLD:1389689-1389689-1389896-1389889-1389891-1379133-1379133-1390979}
  league:
    israel:
      season_id: 27
      leagues:
        - type: NATIONAL_LEAGUE
          name: לאומית
          league_id: 45
          team:
            '1003': מכבי הרצליה
            '5775': מכבי יפו
            '2186': הפועל חדרה
            '2252': הפועל כפר שלם
        - type: WINNER
          name: winner
          league_id: 40
          team:
            '2171': הפועל באר שבע
            '1061': מכבי תל אביב
            '3595': ביתר ירושלים
            '1068': מכבי נתניה
            '2176': הפועל תל אביב
            '1198': מעודון ספורט אשדוד
            '4823': בני סכנין
            '1005': מכבי חיפה
            '2170': הפועל חיפה
            '2182': הפועל קרית שמונה
            '2173': הפועל פתח תקוה
            '5455': עירוני דורות טבריה
            '5981': הפועל ירושלים
            '5257': מכבי בני ריינה











