spring:
  application:
    name: toto
  ai:
    openai:
      api-key: ${PERPLEXITY_API_KEY}
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: sonar
          temperature: 0.3
          max-tokens: 2000
      embedding:
        enabled: false

redis:
  host: ${REDIS_HOST:redis-18068.c83.us-east-1-2.ec2.cloud.redislabs.com}
  port: ${REDIS_PORT:18068}
  password: ${REDIS_PASSWORD}
  expire-seconds: ${REDIS_EXPIRE_SECONDS:86400}




app:
  league:
    israel:
      season_id: 27
      leagues:
        - type: NATIONAL_LEAGUE
          name: לאומית
          league_id: 45
          team:
            '1003': מכבי הרצליה
            '5775': מכבי יפו
            '2186': הפועל חדרה
            '2252': הפועל כפר שלם
        - type: WINNER
          name: winner
          league_id: 40
          team:
            '2171': הפועל באר שבע
            '1061': מכבי תל אביב
            '3595': ביתר ירושלים
            '1068': מכבי נתניה
            '2176': הפועל תל אביב
            '1198': מעודון ספורט אשדוד
            '4823': בני סכנין
            '1005': מכבי חיפה
            '2170': הפועל חיפה
            '2182': הפועל קרית שמונה
            '2173': הפועל פתח תקוה
            '5455': עירוני דורות טבריה
            '5981': הפועל ירושלים
            '5257': מכבי בני ריינה











