spring:
  application:
    name: toto
  ai:
    openai:
      api-key: ${PERPLEXITY_API_KEY}
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: sonar
          temperature: 0.3
          max-tokens: 2000
      embedding:
        enabled: false




app:
  league:
    israel:
      season_id: 27
      leagues:
        - type: NATIONAL_LEAGUE
          name: לאומית
          league_id: 45
        - type: WINNER
          name: winner
          league_id: 40











